# Accuracy: OCRBench

[server]
model_path = "Qwen/Qwen3-VL-8B-Instruct"
extra_args = "--port 3005 --tp-size 1 --enable-multimodal"

[accuracy]
tasks = ["ocrbench"]
extra_args = "--max-tokens 8192 --stream"
