[benchmark]
extra_args = """
    --backend sglang
    --dataset-name image
    --num-prompts 128
    --request-rate 1.0
    --max-concurrency 16
    --random-input-len 512
    --random-output-len 256
    --random-range-ratio 1.0
    --image-count 1
    --image-resolution 1080p
"""
